/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.12.0.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as answers from "../answers.js";
import type * as groups from "../groups.js";
import type * as likedpeople from "../likedpeople.js";
import type * as players from "../players.js";
import type * as questions from "../questions.js";
import type * as questiontemplates from "../questiontemplates.js";
import type * as replies from "../replies.js";
import type * as rooms from "../rooms.js";
import type * as users from "../users.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  answers: typeof answers;
  groups: typeof groups;
  likedpeople: typeof likedpeople;
  players: typeof players;
  questions: typeof questions;
  questiontemplates: typeof questiontemplates;
  replies: typeof replies;
  rooms: typeof rooms;
  users: typeof users;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
